lib/siwapp_web/router.ex
defmodule SiwappWeb.Router do
  use SiwappWeb, :router

  import SiwappWeb.UserAuth

  @env Application.compile_env!(:siwapp, :env)

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SiwappWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug Plug.Parsers, parsers: [:json], json_decoder: Jason
  end

  pipeline :token_authenticated do
    plug SiwappWeb.Plugs.Authenticate
  end

  scope "/api", SiwappWeb do
    pipe_through :api

    post "/sign_in", Api.TokenController, :create
  end

  scope "/graphql" do
    if @env in [:dev, :test] do
      pipe_through :api
      forward "/graphiql", Absinthe.Plug.GraphiQL, schema: SiwappWeb.Schema
    else
      pipe_through [:api, :token_authenticated]
    end

    forward "/", Absinthe.Plug, schema: SiwappWeb.Schema
  end

  # Other scopes may use custom stacks.
  scope "/api", SiwappWeb do
    pipe_through [:api, :token_authenticated]

    get "/invoices/download/:id", Api.InvoicesController, :download
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if @env in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: SiwappWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if @env == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", SiwappWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", SiwappWeb do
    pipe_through [:browser, :require_authenticated_user]

    live_session :user, on_mount: SiwappWeb.UserAuthLive do
      live "/", HomeLive.Index, :index

      get "/users/settings", UserSettingsController, :edit
      put "/users/settings", UserSettingsController, :update
      get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
      live "/users", UsersLive.Index, :index
      live "/users/new", UsersLive.Index, :new
      live "/users/:id/edit", UsersLive.Index, :edit

      live "/series", SeriesLive.Index, :index
      live "/series/new", SeriesLive.Index, :new
      live "/series/:id/edit", SeriesLive.Index, :edit

      live "/taxes", TaxesLive.Index, :index
      live "/taxes/new", TaxesLive.Index, :new
      live "/taxes/:id/edit", TaxesLive.Index, :edit

      live "/invoices/new", InvoicesLive.Edit, :new
      live "/invoices/:id/new", InvoicesLive.Edit, :new
      live "/invoices/:id/edit", InvoicesLive.Edit, :edit
      get "/invoices/:id/show", PageController, :show_invoice
      live "/invoices", InvoicesLive.Index, :index
      live "/customers/:customer_id/invoices", InvoicesLive.Index, :customer
      get "/invoices/:id/download", PageController, :download
      get "/invoices/download/*ids", PageController, :download
      get "/invoices/:id/send_email", PageController, :send_email

      live "/customers/new", CustomersLive.Edit, :new
      live "/customers/:id/edit", CustomersLive.Edit, :edit
      live "/customers/", CustomersLive.Index, :index

      live "/templates", TemplatesLive.Index, :index
      live "/templates/new", TemplatesLive.Edit, :new
      live "/templates/:id/edit", TemplatesLive.Edit, :edit

      live "/recurring_invoices", RecurringInvoicesLive.Index, :index
      live "/recurring_invoices/new", RecurringInvoicesLive.Edit, :new
      live "/recurring_invoices/:id/edit", RecurringInvoicesLive.Edit, :edit

      get "/settings", SettingsController, :edit
      post "/settings", SettingsController, :update

      get "/iframe/:id", IframeController, :iframe

      get "/csv", PageController, :csv
    end
  end

  scope "/", SiwappWeb do
    pipe_through [:browser]
    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/siwapp_web/templates/page/customer_filters.html.heex
<div class="columns">
  <div class="column is-6">
    <label class="label">
      KEY:
    </label>
    <%= text_input(@f, :key, class: "input") %>
  </div>
  <div class="column is-6">
    <label class="label">
      VALUE:
    </label>
    <%= text_input(@f, :value, class: "input") %>
  </div>
</div>

lib/siwapp_web/templates/page/customer_form.html.heex
<fieldset class="fieldset">
  <div class="field is-horizontal field-body">
    <.live_component
      module={SiwappWeb.InvoicesLive.CustomerInputComponent}
      id="customer_input"
      f={@f}
      view={@view}
    />

    <div class="field">
      <%= label(@f, :identification, class: "label") %>
      <p class="control">
        <%= text_input(@f, :identification, phx_debounce: "blur", class: "input") %>
      </p>
      <%= error_tag(@f, :identification) %>
    </div>
  </div>

  <div class="field is-horizontal field-body">
    <div class="field">
      <%= label(@f, :contact_person, class: "label") %>
      <p class="control">
        <%= text_input(@f, :contact_person, phx_debounce: "blur", class: "input") %>
      </p>
      <%= error_tag(@f, :contact_person) %>
    </div>

    <div class="field">
      <%= label(@f, :email, class: "label") %>
      <p class="control">
        <%= text_input(@f, :email, phx_debounce: "blur", class: "input") %>
      </p>
      <%= error_tag(@f, :email) %>
    </div>
  </div>

  <div class="field is-horizontal field-body">
    <div class="field">
      <%= label(@f, :invoicing_address, class: "label") %>
      <p class="control">
        <%= textarea(@f, :invoicing_address, phx_debounce: "blur", class: "textarea") %>
      </p>
      <%= error_tag(@f, :invoicing_address) %>
    </div>

    <div class="field">
      <%= label(@f, :shipping_address, class: "label") %>
      <p class="control">
        <%= textarea(@f, :shipping_address, phx_debounce: "blur", class: "textarea") %>
      </p>
      <%= error_tag(@f, :shipping_address) %>
      <p class="help">
        <a phx-click="copy">
          Copy Invoicing Address
        </a>
      </p>
    </div>
  </div>
</fieldset>

lib/siwapp_web/templates/page/invoice_customer_form.html.heex
<fieldset class="fieldset">
  <h2>Customer</h2>

  <%= render(SiwappWeb.PageView, "customer_form.html", f: @f, view: @view) %>

  <div class="field is-horizontal field-body">
    <div class="field">
      <%= label(@f, :terms, "Legal terms and conditions", class: "label") %>
      <p class="control">
        <%= textarea(@f, :terms, phx_debounce: "blur", class: "textarea") %>
      </p>
      <%= error_tag(@f, :terms) %>
    </div>

    <div class="field">
      <%= label(@f, :notes, class: "label") %>
      <p class="control">
        <%= textarea(@f, :notes, phx_debounce: "blur", class: "textarea") %>
      </p>
      <%= error_tag(@f, :notes) %>
    </div>
  </div>

</fieldset>

lib/siwapp_web/templates/page/invoice_filters.html.heex
<div class="columns">
  <div class="column is-6">
    <label class="label">
      CUSTOMER:
    </label>
    <.live_component
      module={SiwappWeb.InvoicesLive.CustomerInputComponent}
      id="customers"
      f={@f}
      view={:search}
    />
  </div>
  <div class="column is-3">
    <label class="label">
      ISSUE DATE FROM:
    </label>
    <%= date_input(@f, :issue_from_date, class: "input") %>
  </div>
  <div class="column is-3">
    <label class="label">
      TO:
    </label>
    <%= date_input(@f, :issue_to_date, class: "input") %>
  </div>
</div>
<div class="columns">
  <div class="column is-3">
    <label class="label">
      SERIES:
    </label>
    <div class="select is-fullwidth">
      <%= select(@f, :series, ["Choose...": ""] ++ Enum.map(@series_names, &{&1, &1})) %>
    </div>
  </div>
  <div class="column is-3">
    <label class="label">
      NUMBER:
    </label>
    <%= number_input(@f, :number, class: "input") %>
  </div>
  <div class="column is-6">
    <label class="label">
      STATUS:
    </label>
    <div class="select is-fullwidth">
      <%= select(@f, :status,
        "Choose...": "",
        Draft: "draft",
        Paid: "paid",
        Pending: "pending",
        "Past Due": "past_due",
        Failed: "failed"
      ) %>
    </div>
  </div>
</div>
<div class="columns">
  <div class="column">
    <label class="label">
      KEY
    </label>
    <%= text_input(@f, :key, class: "input") %>
  </div>
  <div class="column">
    <label class="label">
      VALUE
    </label>
    <%= text_input(@f, :value, class: "input") %>
  </div>
</div>

lib/siwapp_web/templates/page/invoices_table.html.heex
<table class="table is-fullwidth is-striped is-bordered is-hoverable">
  <thead>
    <tr>
      <%= if @checked != [] do %>
        <th title="">
          <input
            type="checkbox"
            checked={Enum.member?(@checked, 0)}
            phx-click="click_checkbox"
            phx-value-id="0"
          >
        </th>
      <% end %>
      <th title="Reference">
        Reference
      </th>
      <th title="Customer">
        Customer Name
      </th>
      <th title="Date">
        Date
      </th>
      <th title="Sent">
        Sent
      </th>
      <th title="Status" class="has-text-centered">
        Status
      </th>
      <th title="Pending" class="has-text-right">
        Pending
      </th>
      <th title="Total" class="has-text-right">
        Total
      </th>
    </tr>
  </thead>

  <tbody>
    <%= for invoice <- @invoices do %>
      <tr phx-click="redirect" phx-value-id={invoice.id} class="is-clickable">
        <%= if @checked != [] do %>
          <td>
            <input
              type="checkbox"
              phx-click="click_checkbox"
              checked={Enum.member?(@checked, invoice.id)}
              phx-value-id={invoice.id}
            >
          </td>
        <% end %>
        <td>
          <%= SiwappWeb.PageView.reference(invoice.series.code, invoice.number) %>
        </td>
        <td>
          <%= invoice.name %>
        </td>
        <td>
          <%= invoice.issue_date %>
        </td>

        <%= if invoice.sent_by_email do %>
          <td class="icon has-text-success table-icon">
            <i class="fas fa-check"></i>
          </td>
        <% else %>
          <td class="icon has-text-danger table-icon">
            <i class="fas fa-times"></i>
          </td>
        <% end %>

        <%= case Siwapp.Invoices.status(invoice) do %>
          <% :draft -> %>
            <td class="table-span">
              <span class="tag is-info">
                Draft
              </span>
            </td>
            <td></td>

          <% :failed -> %>
            <td class="table-span">
              <span class="tag is-black">
                Failed
              </span>
            </td>
            <td></td>

          <% :paid -> %>
            <td class="table-span">
              <span class="tag is-success">
                Paid
              </span>
            </td>
            <td></td>

          <% :pending -> %>
            <td class="table-span">
              <span class="tag is-warning">
                Pending
              </span>
            </td>
            <td class="has-text-right">
              <%= money_format(invoice.gross_amount - invoice.paid_amount, invoice.currency) %>
            </td>

          <% :past_due -> %>
            <td class="table-span">
              <span class="tag is-danger">
                Past_Due
              </span>
            </td>
            <td class="has-text-right">
              <%= money_format(invoice.gross_amount - invoice.paid_amount, invoice.currency) %>
            </td>
        <% end %>

        <td class="has-text-right">
          <%= money_format(invoice.gross_amount, invoice.currency) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

lib/siwapp_web/templates/page/recurring_invoice_filters.html.heex
<div class="columns">
  <div class="column is-6">
    <label class="label">
      CUSTOMER:
    </label>
    <.live_component
      module={SiwappWeb.InvoicesLive.CustomerInputComponent}
      id="customers"
      f={@f}
      view={:search}
    />
  </div>
  <div class="column is-6">
    <label class="label">
      SERIES:
    </label>
    <div class="select is-fullwidth">
      <%= select(@f, :series, ["Choose...": ""] ++ Enum.map(@series_names, &{&1, &1})) %>
    </div>
  </div>
</div>
<div class="columns">
  <div class="column is-3">
    <label class="label">
      STARTING&nbsp;DATE&nbsp;FROM:
    </label>
    <%= date_input(@f, :starting_from_date, class: "input") %>
  </div>
  <div class="column is-3">
    <label class="label">
      TO:
    </label>
    <%= date_input(@f, :starting_to_date, class: "input") %>
  </div>
  <div class="column is-3">
    <label class="label">
      FINISHING&nbsp;DATE&nbsp;FROM:
    </label>
    <%= date_input(@f, :finishing_from_date, class: "input") %>
  </div>
  <div class="column is-3">
    <label class="label">
      TO:
    </label>
    <%= date_input(@f, :finishing_to_date, class: "input") %>
  </div>
</div>
<div class="columns">
  <div class="column">
    <label class="label">
      KEY
    </label>
    <%= text_input(@f, :key, class: "input") %>
  </div>
  <div class="column">
    <label class="label">
      VALUE
    </label>
    <%= text_input(@f, :value, class: "input") %>
  </div>
</div>

lib/siwapp_web/templates/page/show_invoice.html.heex
<nav class="navbar is-fixed-bottom navbar-menu" role="navigation" aria-label="main navigation">
  <div class="navbar-end navbar-items buttons mr-3">
    <%= link("Back", to: "#", onclick: "history.back()", class: "button is-dark") %>
    <%= link("Send Email",
      to: Routes.page_path(@conn, :send_email, @invoice.id),
      class: "button is-purple"
    ) %>
    <%= link("Download PDF", to: Routes.page_path(@conn, :download, @invoice.id), class: "button is-info") %>
    <%= link("Duplicate", to: Routes.invoices_edit_path(@conn, :new, @invoice.id), class: "button is-info") %>
    <%= link("Edit", to: Routes.invoices_edit_path(@conn, :edit, @invoice.id), class: "button is-info") %>
  </div>
</nav>
<div class="columns is-centered">
  <iframe
    class="iframe template column is-half"
    src={Routes.iframe_path(@conn, :iframe, @invoice.id)}
  ></iframe>
</div>

lib/siwapp_web/templates/page/totals_info.html.heex
<table class="table is-bordered is-narrow">
  <tbody>
    <tr>
      <td class="has-text-weight-bold">
        Gross Amount:
      </td>
      <%= for {currency, total} <- @gross_totals do %>
        <td class="has-text-weight-medium has-text-right">
          <%= money_format(total, currency) %>
        </td>
      <% end %>
    </tr>
    <tr>
      <td class="has-text-weight-bold">
        Net Amount:
      </td>
      <%= for {currency, total} <- @net_totals do %>
        <td class="has-text-weight-medium has-text-right">
          <%= money_format(total, currency) %>
        </td>
      <% end %>
    </tr>
    <%= for {name, list} <- @taxes do %>
      <tr>
        <td class="has-text-weight-bold">
          <%= name %> :
        </td>
        <%= for {currency, total} <- list do %>
          <td class="has-text-weight-medium has-text-right">
            <%= money_format(total, currency) %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>