lib/siwapp_web/router.ex
defmodule SiwappWeb.Router do
  use SiwappWeb, :router

  import SiwappWeb.UserAuth

  @env Application.compile_env!(:siwapp, :env)

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {SiwappWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug Plug.Parsers, parsers: [:json], json_decoder: Jason
  end

  pipeline :token_authenticated do
    plug SiwappWeb.Plugs.Authenticate
  end

  scope "/api", SiwappWeb do
    pipe_through :api

    post "/sign_in", Api.TokenController, :create
  end

  scope "/graphql" do
    if @env in [:dev, :test] do
      pipe_through :api
      forward "/graphiql", Absinthe.Plug.GraphiQL, schema: SiwappWeb.Schema
    else
      pipe_through [:api, :token_authenticated]
    end

    forward "/", Absinthe.Plug, schema: SiwappWeb.Schema
  end

  # Other scopes may use custom stacks.
  scope "/api", SiwappWeb do
    pipe_through [:api, :token_authenticated]

    get "/invoices/download/:id", Api.InvoicesController, :download
  end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if @env in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: SiwappWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if @env == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", SiwappWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", SiwappWeb do
    pipe_through [:browser, :require_authenticated_user]

    live_session :user, on_mount: SiwappWeb.UserAuthLive do
      live "/", HomeLive.Index, :index

      get "/users/settings", UserSettingsController, :edit
      put "/users/settings", UserSettingsController, :update
      get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
      live "/users", UsersLive.Index, :index
      live "/users/new", UsersLive.Index, :new
      live "/users/:id/edit", UsersLive.Index, :edit

      live "/series", SeriesLive.Index, :index
      live "/series/new", SeriesLive.Index, :new
      live "/series/:id/edit", SeriesLive.Index, :edit

      live "/taxes", TaxesLive.Index, :index
      live "/taxes/new", TaxesLive.Index, :new
      live "/taxes/:id/edit", TaxesLive.Index, :edit

      live "/invoices/new", InvoicesLive.Edit, :new
      live "/invoices/:id/new", InvoicesLive.Edit, :new
      live "/invoices/:id/edit", InvoicesLive.Edit, :edit
      get "/invoices/:id/show", PageController, :show_invoice
      live "/invoices", InvoicesLive.Index, :index
      live "/customers/:customer_id/invoices", InvoicesLive.Index, :customer
      get "/invoices/:id/download", PageController, :download
      get "/invoices/download/*ids", PageController, :download
      get "/invoices/:id/send_email", PageController, :send_email

      live "/customers/new", CustomersLive.Edit, :new
      live "/customers/:id/edit", CustomersLive.Edit, :edit
      live "/customers/", CustomersLive.Index, :index

      live "/templates", TemplatesLive.Index, :index
      live "/templates/new", TemplatesLive.Edit, :new
      live "/templates/:id/edit", TemplatesLive.Edit, :edit

      live "/recurring_invoices", RecurringInvoicesLive.Index, :index
      live "/recurring_invoices/new", RecurringInvoicesLive.Edit, :new
      live "/recurring_invoices/:id/edit", RecurringInvoicesLive.Edit, :edit

      get "/settings", SettingsController, :edit
      post "/settings", SettingsController, :update

      get "/iframe/:id", IframeController, :iframe

      get "/csv", PageController, :csv
    end
  end

  scope "/", SiwappWeb do
    pipe_through [:browser]
    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/siwapp_web/views/layout_view.ex
defmodule SiwappWeb.LayoutView do
  use SiwappWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}

  def shared_button(%Phoenix.LiveView.Socket{} = socket) do
    case socket.view do
      n when n in [SiwappWeb.SeriesLive.Index, SiwappWeb.SeriesLive.FormComponent] ->
        new_button("New Series", Routes.series_index_path(socket, :new))

      n when n in [SiwappWeb.CustomersLive.Index, SiwappWeb.CustomersLive.Edit] ->
        new_button("New Customer", Routes.customers_edit_path(socket, :new))

      n when n in [SiwappWeb.TaxesLive.Index, SiwappWeb.TaxesLive.FormComponent] ->
        new_button("New Tax", Routes.taxes_index_path(socket, :new))

      n when n in [SiwappWeb.TemplatesLive.Index, SiwappWeb.TemplatesLive.Edit] ->
        new_button("New Template", Routes.templates_edit_path(socket, :new))

      n when n in [SiwappWeb.RecurringInvoicesLive.Index, SiwappWeb.RecurringInvoicesLive.Edit] ->
        new_button("New Recurring Invoice", Routes.recurring_invoices_edit_path(socket, :new))

      n when n in [SiwappWeb.UsersLive.Index] ->
        new_button("New User", Routes.users_index_path(socket, :new))

      _ ->
        new_button("New Invoice", Routes.invoices_edit_path(socket, :new))
    end
  end

  @spec shared_button(Plug.Conn.t()) :: any()
  def shared_button(%Plug.Conn{} = conn) do
    new_button("New Invoice", Routes.invoices_edit_path(conn, :new))
  end

  def render_search_live(%Phoenix.LiveView.Socket{} = socket) do
    views_with_search = [
      SiwappWeb.InvoicesLive.Index,
      SiwappWeb.CustomersLive.Index,
      SiwappWeb.RecurringInvoicesLive.Index
    ]

    if socket.view in views_with_search do
      view = which_view(socket.view)
      live_component(SiwappWeb.SearchLive.SearchComponent, id: "search", view: view)
    end
  end

  @spec render_search_live(Plug.Conn.t()) :: nil
  def render_search_live(%Plug.Conn{}) do
    nil
  end

  @spec new_button(binary, binary) :: any()
  defp new_button(text, to) do
    live_redirect(text, to: to, method: :get, class: "button is-info")
  end

  @spec which_view(atom()) :: binary()
  def which_view(view) do
    case view do
      SiwappWeb.InvoicesLive.Index ->
        "invoice"

      SiwappWeb.CustomersLive.Index ->
        "customer"

      SiwappWeb.RecurringInvoicesLive.Index ->
        "recurring_invoice"
    end
  end
end

lib/siwapp_web/templates/layout/_user_menu.html.heex
<div class="navbar-item">
  <%= @current_user.email %>
</div>
<%= link "Settings", to: Routes.user_settings_path(@conn, :edit), class: "navbar-item" %>
<%= link "Log out", to: Routes.user_session_path(@conn, :delete), method: :delete, class: "navbar-item"%>

lib/siwapp_web/templates/layout/app.html.heex
<%= render(SiwappWeb.LayoutView, "nav.html", socket_or_conn: @conn, current_user: @current_user) %>
<main class="container section has-navbar-fixed-bottom">
  <%= if info_msg = get_flash(@conn, :info) do %>
    <p class="alert alert-info" role="alert">
      <%= info_msg %>
    </p>
  <% end %>

  <%= if error_msg = get_flash(@conn, :error) do %>
    <p class="alert alert-danger" role="alert">
      <%= error_msg %>
    </p>
  <% end %>

  <%= @inner_content %>
</main>

lib/siwapp_web/templates/layout/live.html.heex
<%= render(SiwappWeb.LayoutView, "nav.html", socket_or_conn: @socket, current_user: @current_user) %>
<main class="container section has-navbar-fixed-bottom">
  <%= if info_msg = live_flash(@flash, :info) do %>
    <p class="alert alert-info" role="alert" phx-click="lv:clear-flash" phx-value-key="info">
      <%= info_msg %>
    </p>
  <% end %>

  <%= if error_msg = live_flash(@flash, :error) do %>
    <p class="alert alert-danger" role="alert" phx-click="lv:clear-flash" phx-value-key="error">
      <%= error_msg %>
    </p>
  <% end %>

  <%= @inner_content %>
</main>

lib/siwapp_web/templates/layout/nav.html.heex
<nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation">
  <div class="navbar-brand pt-2">
    <%= img_tag(Routes.static_path(@socket_or_conn, "/images/logo.svg"))
    |> link(to: Routes.home_index_path(@socket_or_conn, :index), class: "navbar-item") %>
    <a
      role="button"
      class="navbar-burger"
      aria-label="menu"
      aria-expanded="false"
      data-target="navbar-menu"
    >
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <%= if @current_user do %>
    <div class="navbar-menu">
      <div class="navbar-start">
        <%= render_search_live(@socket_or_conn) %>
        <%= live_redirect("Invoices",
          to: Routes.invoices_index_path(@socket_or_conn, :index),
          class: "navbar-item"
        ) %>
        <%= live_redirect("Recurring Invoices",
          to: Routes.recurring_invoices_index_path(@socket_or_conn, :index),
          class: "navbar-item"
        ) %>
        <%= live_redirect("Customers",
          to: Routes.customers_index_path(@socket_or_conn, :index),
          class: "navbar-item"
        ) %>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            Account
          </a>
          <div class="navbar-dropdown">
            <%= live_redirect("Profile",
              to: Routes.user_settings_path(@socket_or_conn, :edit),
              class: "navbar-item"
            ) %>
            <hr class="navbar-divider">
            <%= if @current_user.admin do %>
              <%= live_redirect("Users", to: Routes.users_index_path(@socket_or_conn, :index), class: "navbar-item") %>
              <hr class="navbar-divider">
            <% end %>
            <%= live_redirect("Settings", to: Routes.settings_path(@socket_or_conn, :edit), class: "navbar-item") %>
            <hr class="navbar-divider">
            <%= live_redirect("Series",
              to: Routes.series_index_path(@socket_or_conn, :index),
              class: "navbar-item"
            ) %>
            <%= live_redirect("Taxes", to: Routes.taxes_index_path(@socket_or_conn, :index), class: "navbar-item") %>
            <%= live_redirect("Templates",
              to: Routes.templates_index_path(@socket_or_conn, :index),
              class: "navbar-item"
            ) %>
            <hr class="navbar-divider">
            <%= link("Log out",
              to: Routes.user_session_path(@socket_or_conn, :delete),
              method: :delete,
              class: "navbar-item"
            ) %>
          </div>
        </div>
      </div>

      <div class="navbar-end">
        <div class="navbar-item">
          <%= shared_button(@socket_or_conn) %>
        </div>
      </div>
    </div>
  <% end %>
</nav>

lib/siwapp_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= csrf_meta_tag() %>
    <%= live_title_tag(assigns[:page_title] || "Welcome", prefix: "Siwapp - ") %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")} />
    <script
      defer
      phx-track-static
      type="text/javascript"
      src={Routes.static_path(@conn, "/assets/app.js")}
    >
    </script>
    <script src="https://kit.fontawesome.com/138af46218.js" crossorigin="anonymous">
    </script>
  </head>

  <body class="has-navbar-fixed-top content">
    <%= @inner_content %>
  </body>
</html>

lib/siwapp_web/templates/layout/search.html.heex
<form class="navbar-item is-active">
  <div class="search-input">
    <button id="search-button" class="button" type="button">
      <span class="icon is-small">
        <i class="fas fa-angle-down" aria-hidden="true"></i>
      </span>
    </button>
    <input class="input" type="search" placeholder="Search..."/>
    <button class="button is-info" type="submit">
      <span class="icon is-small is-right"><i class="fas fa-search"></i></span>
    </button>
  </div>

  <div class="search-menu">
    <div class="search-menu-content" id="search-menu">
      <div class="columns">
        <div class="column is-6">
          <label class="label">CUSTOMER:</label>
          <div class="select is-fullwidth">
            <select>
              <option>Choose...</option>
              <option>With options</option>
            </select>
          </div>
        </div>
        <div class="column is-3">
          <label class="label">ISSUE DATE FROM:</label>
          <input class="input" type="date">
        </div>
        <div class="column is-3">
          <label class="label">TO:</label>
          <input class="input" type="date">
        </div>
      </div>
      <div class="columns">
        <div class="column is-3">
          <label class="label">SERIES:</label>
          <div class="select is-fullwidth">
            <select>
              <option>Choose...</option>
              <option>With options</option>
            </select>
          </div>
        </div>
        <div class="column is-3">
          <label class="label">NUMBER:</label>
          <input class="input" type="text">
        </div>
        <div class="column is-6">
          <label class="label">STATUS:</label>
          <div class="select is-fullwidth">
            <select>
              <option>Choose...</option>
              <option>With options</option>
            </select>
          </div>
        </div>
      </div>
      <div class="columns">
        <div class="column">
          <label class="label">TAGS</label>
          <input class="input" type="text">
        </div>
        <div class="column">
          <label class="label">META</label>
          <input class="input" type="text">
        </div>
      </div>
      <div class="buttons is-right">
        <button class="button is-info">Export to csv</button>
        <button class="button is-info">Search</button>
      </div>
    </div>
  </div>
</form>